# Object Definitions
==================================================================================================================================
btn_createNotification                       xpath           //button[text()='Create new notification']
div_selectMonitor                            xpath           //div[text()='Select monitors'] 
div_monitorName                              xpath           //div[text()='${monitorName}']  
div_commentSection                           xpath           //textarea[@placeholder='Work being done']
div_endTimeBox                               xpath           (//b[text()='End time']/..//div//input[@class='form-control'])[1]
div_startTimeBox                             xpath           (//b[text()='Start time']/..//div//input[@class='form-control'])[1]
div_selectTimeMode                           xpath           //button[text()='Time']
btn_close                                    xpath           //button[text()='Close']
div_mintueSlider                             xpath           (//div[@class='handle'])[2]
div_endTimeSecondBox                         xpath           (//b[text()='End time']/..//div//input[@class='form-control'])[2]
div_startTimeSecondBox                       xpath           (//b[text()='Start time']/..//div//input[@class='form-control'])[2]
span_notification                            xpath           //span[contains(text(),'${message}')]     
input_searchBox                              xpath           //input[@id='searchText']
span_deleteNotification                      xpath           //*[text()='${message}']/ancestor::tr//span[contains(@class,'glyphicon')]
button_delete                                xpath           //button[text()='Delete']
btn_ok                                       xpath           //button[text()='OK']
btn_save                                     xpath           //button[text()='Save']
input_enabledCheckBox                        xpath           //div[@id='enabled']//input[@type='checkbox']  
input_overrideCheckBox                       xpath           //div[@id='override']//input[@type='checkbox']
div_eventContainer                           xpath           //div[@class='event-item-container']
div_eventType                                xpath           //div[text()="${eventType}"]
link_Message                                 xpath           //span[text()='${message}']
td_monitorName                               xpath           //td[@data-search-text='']
span_notificationWithLogo                    xpath           //div[@class='cell-status-container empty']/ancestor::tr//span[contains(text(),'${message}')]   
div_logo                                     xpath           //div[@class='cell-status-container empty']    
span_redNotificationWithLogo                 xpath           //div[@class='cell-status-container red']/ancestor::tr//span[contains(text(),'${message}')]
span_greenNotificationWithLogo               xpath           //div[@class='cell-status-container green']/ancestor::tr//span[contains(text(),'${message}')] 
span_orangeNotificationWithLogo              xpath           //div[@class='cell-status-container orange']/ancestor::tr//span[contains(text(),'${message}')]
td_currentTime                               xpath           (//td[contains(@style,'white-space')])[1]
div_greenColor                               xpath           //td[text() ='${currentTime}']/ancestor::tr//div[@class='green']
div_RegTestColor                             xpath           //tr//div[@class='${color}']
link_systemName                              xpath           //tr//a[text()='${systemName}'] 
div_systemWithText                           xpath           //div[text()='${systemName}']
div_accessLevel                              xpath           //div[@id='access-level']//div[@class='rw-input'] 
div_publicSystem                             xpath           //div[contains(@style,'${systemName}')]    
div_endDate                                  xpath           //div[@class='endDate']//input[@type='checkbox']    
link_Role                                    xpath           //tr//a[text()='${role}']   
span_permission                              xpath           //span[@class='Select-arrow']
div_selectFQAs                               xpath           //div[@class='Select-menu']//div[text()='${faq}'] 
div_newFaqs                                  xpath           //div[contains(text(),'Add a section')]
link_faqsLink                                xpath           //a[text()='FAQ']
div_deleteFAQsPermission                     xpath           //*[text()='${faqPermission}']/parent::div[@class='Select-value']//span[@class='Select-value-icon']                                                                    
span_Name                                    xpath           //label[contains(text(),'Name')] 
list_adminMenu                               xpath           //li[@class='login-tab dropdown']
link_adminPage                               xpath           //a[text()='Admin page'] 
link_RegressionTest                          xpath           //a[text()='Regression Test 2']
link_RegressionMonitor                       xpath           //a[text()='${monitorName}']   
btn_saveAnyway                               xpath          //button[text()='Save anyway']   
not_firstpagetop                             xpath           (//li/a[text()='${i}'])[1]    
not_firstpagebottom                          xpath           (//li/a[text()='${j}'])[2]
banner_notifcation                           xpath           //a[contains (text(), 'Banner notifications')]
Last_update                                  xpath           (//div[contains (text(), 'Last updated')])[1]
All_System                                   xpath           //div[contains(text(),'All systems')]
4LTR_Press                                   xpath           //li[contains(text(),'4LTR Press')]
validate_filter                              xpath           //tbody//td[2][contains(@data-search-text,'4LTR Press')]
validate_4LTR_Press                          xpath            (//div[contains(text(),'4LTR Press')])[1]


==================================================================================================================================
    